# 服务提供者端口号
server:
  port: 8090

spring:
  # 服务名称
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shuniversity/microservice-config.git

eureka:
  instance:
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:123456@eureka-server:8761/eureka/

logging:
  level:
    root: debug